# Generated by Django 5.1.6 on 2025-02-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='face_embedding',
        ),
        migrations.AddField(
            model_name='user',
            name='face_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
